[package]
name = "vectored-queue"
version = "0.1.0"
edition = "2021"

[features]
sync = []
async = ["dep:futures", "dep:tokio"]

[dependencies]
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = ["sync"], optional = true }
thiserror = "1"
